### ISSUE TITLE
Problem with findContact by SMS API

### ISSUE THREAD

**Issue by piotrp321** [smsapi/smsapi-php-client#89] opened 2020-05-07 13:41 UTC
Hello 

I have a searching phone number like this:

    /**
     * @param string $phone
     * @return array
     */
    public function findByPhone(string $phone): array
    {
        $params = new FindContactsBag();
        $params->phoneNumber = $phone;

        return $this->getService()->contactsFeature()->findContacts($params);
    }

And sometimes this code return error 

Argument 2 passed to Smsapi\Client\Feature\Contacts\Data\ContactCustomFieldFactory::create() must be of the type string, int given, called in ...../vendor/smsapi/php-client/src/Feature/Contacts/Data/ContactFactory.php on line 66

**Comment by maciejlew** [comment] 2020-05-08 13:36
I cannot reproduce this issue. Could you provide us with more details? You can also contact SMSAPI support so we would be able to track your issue.

**Comment by piotrp321** [comment] 2020-05-11 09:13
Ok, i am trying do debug this problem. I have a fix

vendor/smsapi/php-client/src/Feature/Contacts/Data/ContactFactory.php

    private function createCustomFieldsFromObject(stdClass $object): array
    {
        $objectCustomFieldsProperties = array_filter(
            get_object_vars($object),
            [$this, 'isCustomFieldProperty'],
            ARRAY_FILTER_USE_KEY
        );

        $customFields = [];

        foreach ($objectCustomFieldsProperties as $name => $value) {
            $customFields[] = $this->contactCustomFieldFactory->create($name, (string)$value);
        }

        return $customFields;
    }

I added transform value to string because in my case $objectCustomFieldsProperties look like that:

![image](https://user-images.githubusercontent.com/10939014/81544950-75cdc680-9378-11ea-8351-aceb783ba27a.png)

**Comment by maciejlew** [comment] 2020-05-13 06:53
Thanks for your input. The problem is somewhere else. The 'undelivered messages' contact field is dynamic and was mistakenly omitted on built in contact fields list.

Fix is already in master branch. It is now under code review and test. It will be included in next minor release.

**Closed** 2020-05-14 10:47 UTC
Labels: bug
